import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { Box } from '@mui/material';
import NavBar from '../components/NavBar';
import { Roboto } from 'next/font/google';
import theme from '../theme';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Box display="flex" minHeight="100vh">
              <NavBar />
              <Box
                component="main"
                flexGrow={1}
                p={2}
                sx={{
                  overflowY: 'auto',
                  ml: '350px',
                }}
              >
                {children}
              </Box>
            </Box>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
